
name: Search GitHub Users, Find Newest Member, and Get Join Date/Time

on:
  workflow_dispatch: # Manual trigger

jobs:
  search_users:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Search users (using API)
        id: search
        run: |
          SEARCH_RESULT=$(curl -s "https://api.github.com/search/users?q=location:Bangalore+followers:>110&per_page=100" | jq '.items[] | {login, name, location, followers, created_at}') # No -r here!
          # Check if the result is a single object or an array
          if [[ "$SEARCH_RESULT" == "null" ]]; then
            echo "No users found"
            exit 0 # Exit successfully if no users are found
          elif echo "$SEARCH_RESULT" | jq -e 'type == "array"' > /dev/null; then
            echo "$SEARCH_RESULT" > users.json # It's an array, write directly
          else
            echo "[$SEARCH_RESULT]" > users.json # It's a single object, wrap in array
          fi
          echo "Search results saved to users.json"
