name: Extract and Sort Users

on:
  workflow_dispatch:

jobs:
  extract_users:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract and sort users
        run: |
          gh search users "location:Bangalore followers:>110" --json name,location,created_at | jq -r '.items[] | {name, location, created_at} | sort_by(.created_at) | reverse | .[:10]' > users_sorted.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: users-data
          path: users_sorted.json
