name: Get My GitHub Data

on:
  workflow_dispatch:

jobs:
  get_my_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get My Data
        run: |
          # Replace YOUR_GITHUB_USERNAME with your actual GitHub username
          USERNAME="danielrayappa2210" 
          curl -s "https://api.github.com/users/$USERNAME" > my_data.json
          echo "My data saved to my_data.json"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-github-data
          path: my_data.json

      - name: Display JSON Content (optional)
        run: cat my_data.json
