jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        run: |
          SEARCH_RESULT=$(curl -s "https://api.github.com/search/users?q=location:Bangalore+followers:>110&per_page=100" | jq '.items[] | {login, name: .user.name, location: .user.location, followers: .user.followers, created_at: .user.created_at}') # Corrected jq filter
          echo "$SEARCH_RESULT" > users.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: users-data
          path: users.json

      - name: Download artifact (if needed)
        uses: actions/download-artifact@v4
        with:
          name: users-data
          path: ./

      - name: Use the data (example)
        run: cat users.json
